# .gitlab-ci.yml

stages:
  - install
  - test

image: node:12

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  script:
    - npm run test