# .gitlab-ci.yml

stages:
  - install
  - test
  - build

image: node:12

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  script:
    - npm run test

lint:
  stage: test
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build