version: 2.1

# workflows

workflows:
  version: 2.1
  dgsdsd-workflow:
    jobs:
      - test

# jobs

jobs:

  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: node --version
      - run: npm ci
      - run: npm test